name: Manual IPA JSON Update

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download URL of the IPA file'
        required: true
      version:
        description: 'Version of the app (e.g., 9.0.72)'
        required: true
      description:
        description: 'Update description for apps.json'
        required: true
      release_date:
        description: 'Release date (YYYY-MM-DD)'
        required: true

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Update apps.json
        shell: python
        run: |
          import os, json

          ipa_url = os.environ["INPUT_IPA_URL"]
          version = os.environ["INPUT_VERSION"]
          description = os.environ["INPUT_DESCRIPTION"]
          release_date = os.environ["INPUT_RELEASE_DATE"]

          repo = os.environ['GITHUB_REPOSITORY']

          # Hardcoded IPA size 90 MB
          size = 90000000

          apps_data = {
              "name": "EeveeSpotify",
              "identifier": "com.eevee.source",
              "author": "whoeevee",
              "apps": [
                  {
                      "name": "EeveeSpotify",
                      "bundleIdentifier": "com.spotify.client",
                      "developerName": "EeveeSpotify Team",
                      "version": version,
                      "versionDate": release_date,
                      "versionDescription": description,
                      "downloadURL": ipa_url,
                      "iconURL": f"https://raw.githubusercontent.com/{repo}/main/images/icon.png",
                      "localizedDescription": description,
                      "caption": f"Spotify v{version} injected with EeveeSpotify",
                      "description": f"Spotify v{version} injected with EeveeSpotify",
                      "screenshotURLs": [
                          f"https://raw.githubusercontent.com/{repo}/main/images/Edited_1.jpg",
                          f"https://raw.githubusercontent.com/{repo}/main/images/unlimited_skips.jpg",
                          f"https://raw.githubusercontent.com/{repo}/main/images/lyrics.jpg"
                      ],
                      "size": size
                  }
              ],
              "subtitle": f"Spotify v{version}",
              "news": []
          }

          with open("apps.json", "w") as f:
              json.dump(apps_data, f, indent=2)

          print("apps.json updated successfully")

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add apps.json
          git commit -m "Update apps.json for ${{ github.event.inputs.version }}" || echo "No changes to commit"
          git push